# Generated by Django 4.0 on 2021-12-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='ApplicationModel',
        ),
    ]
